version: '3'

services:
 db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    container_name: "Tienda-DB"
    volumes:
      - tienda-db:/data/db

volumes:
  tienda-db:
    external: false